### PR TITLE
Update RobloxHomePatcher.py, taking account for partial patches and installations to "Program Files (x86)".

### PR DESCRIPTION
**Pull request by Windows81**

### CODE REVIEW

**Comment by 1011025m** [comment]
This is quite new to me - I have not actually seen any Roblox installations into the Program Files folder. Can you name any instances of that happening?

I can probably make it pull from the registry key (where the roblox path lies) if the location varies a lot.

**Comment by 1011025m** [comment]
Apparently This is a thing that actually happens. I'll merge your PR and make a new release.

**Comment by 1011025m** [comment]
Welp, I should've tested your script before merging it. It'd just throw an error if Roblox isn't in LOCALAPPDATA.

**Comment by 1011025m** [comment]
I'm really sorry about merging your PR. Most of the modifications that you made don't match what I want the script to do. This is my mistake.

**Comment by Windows81** [comment]
My own installation of Rōblox strangely enough was placed in Program
Files.  I installed it in May 2020 and may have allowed the installation to
run with elevated UAC.  I don't recommend including a custom registry key,
as you're only looking within very few folders in the entire system.

**Comment by Windows81** [comment]
My changes might've not errored out on my end because there were fragments of older versions of Rōblox executables in the appdata folder.  Thanks for taking the time to test my changes out!

**Pull request merged**
