### PR TITLE
only import what's needed

### PR DESCRIPTION
**Pull request by lolmanurfunny**

### CODE REVIEW

**Comment by 1011025m** [comment]
This is unnecessary - in fact, I built the executable with only the selected imports and the file size change is so negligible. I'm not sure if you're just trying to claim some "credit" here.

It's funny that I briefly looked into your repository and there's a PR that does the exact same thing to your script - this is just the easiest PR of all time......

**Comment by lolmanurfunny** [comment]
> I'm not sure if you're just trying to claim some "credit" here.

Just trying to improve your script. No need to overthink a pull request.

> I briefly looked into your repository and there's a PR that does the exact same thing to your script

Just paying it forward is all.

**Comment by lolmanurfunny** [comment]
image

**Comment by 1011025m** [comment]
That's huge effort to make a meme rather than being more concrete with your help.

**Comment by lolmanurfunny** [comment]
> huge effort

No, not much effort was required of me to produce such fine art. It was made in my browser.

**Pull request closed without merging**
